// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"time"
)

type Article struct {
	ID          int64
	Slug        string
	Title       string
	Description string
	Body        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	AuthorID    int64
}

type ArticleTag struct {
	ArticleID int64
	TagID     int64
	CreatedAt time.Time
}

type Comment struct {
	ID        int64
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
	AuthorID  int64
	ArticleID int64
}

type Favorite struct {
	UserID    int64
	ArticleID int64
	CreatedAt time.Time
}

type Following struct {
	UserID     int64
	FollowerID int64
	CreatedAt  time.Time
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	Bio       *string
	Image     *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
